const express=require('express'),path=require('path'),crypto=require('crypto'),bcrypt=require('bcryptjs');
const {Pool}=require('pg'),session=require('express-session'),pgSession=require('connect-pg-simple')(session),rateLimit=require('express-rate-limit');
const app=express(),PORT=process.env.PORT||10000,DB=process.env.DATABASE_URL,OTP_MODE=(process.env.OTP_MODE||'test').toLowerCase(),TEST_OTP=process.env.TEST_OTP||'123456',TTL=Number(process.env.OTP_TTL_SECONDS||300);
const pool=DB?new Pool({connectionString:DB,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
app.use(express.json());app.use(express.urlencoded({extended:false}));
app.use(session(pool?{store:new pgSession({pool,tableName:'user_sessions',createTableIfMissing:true}):{},secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:28800000}}));
app.use(express.static(path.join(__dirname,'public')));
const limiter=rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:true,legacyHeaders:false});
async function init(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,identifier TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,full_name TEXT NOT NULL DEFAULT 'ARAYA User',mobile TEXT,role TEXT NOT NULL DEFAULT 'member',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS otp_challenges(id UUID PRIMARY KEY,user_id BIGINT REFERENCES users(id),identifier TEXT NOT NULL,mode TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL,attempts INT DEFAULT 0,verified BOOLEAN DEFAULT FALSE,created_at TIMESTAMPTZ DEFAULT NOW());`);if(process.env.SEED_DEMO_USER==='true'){const q=await pool.query('SELECT id FROM users WHERE identifier=$1',['demo']);if(!q.rowCount)await pool.query('INSERT INTO users(identifier,password_hash,full_name) VALUES($1,$2,$3)',['demo',await bcrypt.hash(process.env.DEMO_PASSWORD||'ChangeMe123!',12),'ARAYA Demo User']);}}
async function user(id){if(!pool)return null;const q=await pool.query('SELECT * FROM users WHERE identifier=$1',[id]);return q.rows[0]||null;}
async function twilioStart(to){const a=process.env.TWILIO_ACCOUNT_SID,t=process.env.TWILIO_AUTH_TOKEN,s=process.env.TWILIO_VERIFY_SERVICE_SID;if(!a||!t||!s)throw Error('Twilio configuration missing');const r=await fetch(`https://verify.twilio.com/v2/Services/${s}/Verifications`,{method:'POST',headers:{Authorization:'Basic '+Buffer.from(a+':'+t).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({To:to,Channel:'sms'})});const d=await r.json();if(!r.ok)throw Error(d.message||'OTP provider error');return d;}
async function twilioCheck(to,code){const a=process.env.TWILIO_ACCOUNT_SID,t=process.env.TWILIO_AUTH_TOKEN,s=process.env.TWILIO_VERIFY_SERVICE_SID;const r=await fetch(`https://verify.twilio.com/v2/Services/${s}/VerificationCheck`,{method:'POST',headers:{Authorization:'Basic '+Buffer.from(a+':'+t).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({To:to,Code:code})});const d=await r.json();return r.ok&&d.status==='approved';}
app.get('/api/health',(req,res)=>res.json({service:'ARAYA',status:'ok',databaseConfigured:!!pool,otpMode:OTP_MODE}));
app.post('/api/auth/login',limiter,async(req,res)=>{const id=String(req.body?.identifier||'').trim(),pw=String(req.body?.password||'');if(!id||!pw)return res.status(400).json({message:'User ID/mobile and password are required.'});let u=await user(id);if(!u&&OTP_MODE==='test'&&id==='demo'){u={id:0,identifier:'demo',full_name:'ARAYA Demo User',mobile:process.env.DEMO_MOBILE||null,role:'member',active:true,password_hash:await bcrypt.hash(process.env.DEMO_PASSWORD||'ChangeMe123!',10)};}if(!u||!u.active||!(await bcrypt.compare(pw,u.password_hash)))return res.status(401).json({message:'Invalid login details.'});if(OTP_MODE==='twilio'){if(!u.mobile)return res.status(400).json({message:'No mobile number is configured for this account.'});try{await twilioStart(u.mobile);}catch(e){return res.status(502).json({message:'Unable to send OTP. Check OTP provider settings.'});}}
if(!pool&&OTP_MODE!=='test')return res.status(503).json({message:'Connect PostgreSQL before production authentication.'});let cid=crypto.randomUUID();if(pool)await pool.query('INSERT INTO otp_challenges(id,user_id,identifier,mode,expires_at) VALUES($1,$2,$3,$4,NOW()+($5||\' seconds\')::interval)',[cid,u.id,id,OTP_MODE,TTL]);req.session.pending={id:u.id,identifier:id,challenge:cid};res.json({success:true,otpRequired:true,challengeId:cid,expiresIn:TTL,testMode:OTP_MODE==='test'});});
app.post('/api/auth/verify-otp',limiter,async(req,res)=>{const cid=String(req.body?.challengeId||''),code=String(req.body?.code||'').trim(),p=req.session.pending;if(!p||p.challenge!==cid)return res.status(400).json({message:'OTP session expired. Login again.'});let approved=false;if(OTP_MODE==='test')approved=code===TEST_OTP;else{const u=await user(p.identifier);if(u?.mobile)approved=await twilioCheck(u.mobile,code);}if(!approved){if(pool)await pool.query('UPDATE otp_challenges SET attempts=attempts+1 WHERE id=$1',[cid]);return res.status(401).json({message:'Incorrect or expired OTP.'});}if(pool)await pool.query('UPDATE otp_challenges SET verified=true WHERE id=$1',[cid]);req.session.regenerate(e=>{if(e)return res.status(500).json({message:'Could not create session.'});req.session.user={id:p.id,identifier:p.identifier};res.json({success:true});});});
app.post('/api/auth/resend-otp',limiter,async(req,res)=>{const p=req.session.pending;if(!p)return res.status(400).json({message:'Login again to request an OTP.'});if(OTP_MODE==='twilio'){const u=await user(p.identifier);if(!u?.mobile)return res.status(400).json({message:'No mobile number configured.'});try{await twilioStart(u.mobile);}catch{return res.status(502).json({message:'Unable to send OTP.'});}}const cid=crypto.randomUUID();p.challenge=cid;if(pool)await pool.query('INSERT INTO otp_challenges(id,user_id,identifier,mode,expires_at) VALUES($1,$2,$3,$4,NOW()+($5||\' seconds\')::interval)',[cid,p.id,p.identifier,OTP_MODE,TTL]);res.json({success:true,challengeId:cid,expiresIn:TTL,testMode:OTP_MODE==='test'});});
app.get('/api/auth/me',(req,res)=>req.session.user?res.json({authenticated:true,user:req.session.user}):res.status(401).json({authenticated:false}));
app.post('/api/auth/logout',(req,res)=>req.session.destroy(()=>res.json({success:true})));
app.use((req,res)=>res.sendFile(path.join(__dirname,'public','login.html')));
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`ARAYA running on port ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
